title = "CCAI"
baseURL = "https://ccai.willitcode.com"
theme = "ananke"

[params]
background_color_class = "bg-dark-green"
# Can't figure out how to get this to tint the image
# without also dimming the text
#cover_dimming_class = "bg-dark-green o-60"

[[menus.main]]
    name = "The Problem"
    url = "/problem"
    weight = 1

[[menus.main]]
    name = "The Causes" # alt title: Why It's Happening
    url = "/causes"
    weight = 2

[[menus.main]]
    name = "The Impacts"
    url = "/impacts"
    weight = 3

[[menus.main]]
    name = "Our Solutions"
    url = "/solutions"
    weight = 4
